name: Elixir CI
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: graphql-query-elixir-ci-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_BUILD: true
  MIX_ENV: test

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - otp_version: "28.0"
            elixir_version: "1.19.0-rc.0-otp-28"
          - otp_version: "27.3"
            elixir_version: "1.18"
          - otp_version: "26.2"
            elixir_version: "1.17"
          - otp_version: "25.3"
            elixir_version: "1.17"
          - otp_version: "24.3"
            elixir_version: "1.15"

    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            _build/test/lib/graphql_query/native/graphql_query_native
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: test-native-${{ runner.os }}-${{ hashFiles('native/**/Cargo.lock') }}
          restore-keys: |
            test-native-${{ runner.os }}

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp_version }}
          elixir-version: ${{ matrix.elixir_version }}

      - name: Install deps
        run: mix deps.get

      - name: Compile deps
        run: mix deps.compile

      - name: Check format
        run: mix format --check-formatted

      - name: Run Credo
        run: mix credo

      - name: Restore dialyzer cache
        uses: actions/cache/restore@v4
        with:
          path: priv/plts
          key: plts-v1-${{ matrix.otp_version }}-${{ matrix.elixir_version }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            plts-v1-${{ matrix.otp_version }}-${{ matrix.elixir_version }}-

      - name: Run dialyzer
        run: mix dialyzer --format github

      - name: Save dialyzer cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: priv/plts
          key: plts-v1-${{ matrix.otp_version }}-${{ matrix.elixir_version }}-${{ hashFiles('mix.lock') }}

      - name: Run tests
        run: mix test --warnings-as-errors

      - name: Compile once again but without optional deps
        run: mix compile --force --warnings-as-errors --no-optional-deps

      - name: All top level modules exists on mix.exs
        run: bash ./bin/check_modules_docs.sh
